const tekst = {
    splitD: 'Split klima uređaji su vrsta klimatizacijskih sistema koji se sastoje od dva glavna dela: unutrašnje jedinice i spoljne jedinice.Većina modernih modela koristi invertersku tehnologiju, koja omogućava prilagođavanje brzine kompresora i održavanje stabilne temperature sa manjom potrošnjom energije. Ovo može rezultirati smanjenim računima za struju u poređenju sa neefikasnim sistemima. Postoje različiti stilovi i veličine unutrašnjih jedinica, tako da možete izabrati onu koja odgovara vašim preferencijama i enterijeru prostorije. Ovi uređaji se često koriste za klimatizaciju pojedinačnih prostorija ili manjih prostorija.',
    multiD: 'Multi klima uređaji, takođe poznati kao multi-split sistemi, su vrsta klimatizacijskih sistema koji omogućavaju klimatizaciju više prostorija ili zona. Sastoji se od jedne spoljne jedinice i minimalno 2 unutrašnje jedinice i svaka unutrašnja jedinica je direktno povezana sa spoljnom jedinicom. Ovi uređaji pružaju fleksibilnost i mogućnost nezavisne kontrole temperature u različitim prostorijama. Svaka unutrašnja jedinica ima svoj daljinski upravljač koji omogućava korisnicima da podešavaju i održavaju željenu temperaturu za svaki prostor. Multi klima uređaji često koriste invertersku tehnologiju kako bi postigli veću energetsku efikasnost što rezultira manjom potrošnjom energije i uštedom na računima za struju. Postoje različiti stilovi i veličine unutrašnjih jedinica, tako da možete izabrati onu koja odgovara vašim preferencijama i enterijeru prostorije.',
    kanalskiD: 'Kanalni klima uređaji su sistemi za klimatizaciju koji se koriste za hlađenje i grejanje prostora. Ovi uređaji često se koriste u komercijalnim ili većim stambenim zgradama, kao što su kancelarije, hoteli, prodavnice i restorani. Kanalni klima uređaji su takođe poznati kao centralni klima uređaji. Sastoji se od jedne spoljne jedinice i jedne unutrašnje jedinice u kojoj se vazduh hladi ili greje i nakon toga se putem kanala prenosi u različite prostorije ili zone. Kanali su obično smešteni u plafonu ili pod plafonom i mogu biti ravni ili okrugli.',
    podnoD: 'Podno grejanje je sistem grejanja koji se koristi za zagrevanje prostora putem toplote koja se emituje direktno sa poda. Umesto tradicionalnih radijatora ili grejnih tela na zidovima, podno grejanje koristi sistem cevi koji se nalazi ispod podne obloge. Obično se koriste fleksibilne plastične cevi, najčešće od polietilena ili polibutilena, koje se postavljaju u zavojnice ili mreže. Kroz ove cevi cirkuliše topla voda koja dolazi iz glavnog sistema grejanja. Toplota se prenosi sa cevi na pod i zatim se ravnomerno širi po prostoru. Vodeno podno grejanje zahteva profesionalnu instalaciju i može se koristiti sa različitim izvorima toplote, kao što su gasni ili električni kotlovi, toplotne pumpe ili solarni sistemi. Prednosti podnog grejanja: ravnomerna raspodela toplote, ušteda prostora, tih rad, energetska efikasnost kao i jednostavno podešavanje temperature.',
    radijatorD: 'Radijatorsko grejanje je jedan od najčešće korišćenih sistema grejanja u domovima, poslovnim prostorima i industrijskim objektima. Ovaj sistem se zasniva na korišćenju radijatora ili grejnih tela postavljenih na zidovima prostorija radi emitovanja toplote i zagrevanja vazduha u prostoru. Radijatorsko grejanje koristi kotao za zagrevanje vode koja cirkuliše kroz cevi i prenosi toplotu na radijatore. Radijatori emituju toplotu u prostoriju čime se zagreva vazduh i postiže željena temperatura u prostoru. Termostati se koriste za kontrolu temperature, omogućavajući precizno podešavanje grejanja prema potrebama korisnika. Redovno održavanje sistema je važno kako bi se osigurala optimalna performansa i dugotrajnost sistema.',
    ventilacijaD: 'Ventilacija je proces obezbeđivanja svežeg vazduha u zatvorenim prostorima, kao i uklanjanja zagađenog vazduha i neprijatnih mirisa. Ovaj proces se ostvaruje kroz sistem ventilacije koji omogućava protok vazduha između spoljnog okruženja i unutrašnjosti prostorija. Mehanička ventilacija koristi ventilacione sisteme, kao što su ventilatori i ventilacione kanale, kako bi aktivno izvlačila zagađeni vazduh iz prostorija i dovođenjem svežeg vazduha iz spoljnog okruženja u različite prostorije. Ventilacioni sistemi često koriste filtere kako bi se uklonile čestice prašine, polena, alergena i drugih zagađivača iz vazduha. Filtracija vazduha poboljšava kvalitet vazduha i smanjuje rizik od respiratornih problema.',
}

export default tekst;