import images from '../../../data/Images/images';

export const serviceTypes = {
  ciscenjeKlime: {
    title: 'Čišćenje klima uređaja',
    text: 'Čišćenje klima uređaja započinjemo skidanjem poklopca. Zatim vadimo filtere, skidamo krilca i skidamo kompletne plastike. U zavisnosti od stanja klime skidamo i turbinu (ne ulazi u osnovnu cenu servisa). Komplet plastike, filtere i turbine peremo i vraćamo u fabričko stanje. Dok se to suši peremo i dezinfikujemo kompletno saće (isparivač) unutrašnje jedinice sredstvom koje u sebi ima visok procenat asepsola. Nakon što to uradimo sklapamo klima uređaj. Naša je obaveza da Vam dodatno skrenemo pažnju da ukoliko se klima uređaj koristi u poslovnim prostorijama, prostorijama u kojima radi veliki broj zaposlenih, bolnicama, frizerskim salonima, prodavnicama i slično, servisiranje je potrebno izvršiti nekoliko puta godišnje, po mogućstvu na tri meseca. Na taj način sprečavate širenje virusa i bakterija na isparivaču i turbini unutrašnje jedinice preko kojih se paraziti raspršuju u prostor. Budite odgovorni i redovno servisirajte klima uređaj kako bi Vas isti dobro služio dugi niz godina i kako bi očuvali zdravlje Vaše porodice ili Vaših kolega.',
    img: images.ciscenjeKlimaUredjaja,
    galleryUrl: '/galerija/servis-klima-uređaja',
  },
  popravkaElektronike: {
    title: 'Popravka elektronike',
    text: 'Vršimo popravku i servisiranje elektronike na inverter i standardnim klima uređajima. Nakon što nas pozovete i u telefonskom razgovoru predočite problem, naš majstor će izaći na teren kako bi obavio pregled klima uređaja u cilju utvrđivanja problema. Potrebno je da utvrdi da li je problem u samoj elektronici ili u nekom drugom segmentu. Ukoliko majstor ustanovi da je problem u elektronici demontiraćemo je sa uređaja kako bi je odneli u naš servis gde će je naš elektroničar vratiti u prvobitno stanje. Naravno kada uradimo defektažu, kontaktiraćemo Vas kako bi Vam saopštili cenu popravke i ukoliko odobrite naš elektroničar otpočinje popravku. Popravka elektronike kod inverter klima je malo složeniji proces, iz razloga što se oštećenje nekada ne može prepoznati u startu, u tom slučaju pristupamo defektaži na samom uređaju, a to je intervencija koja oduzima više vremena. Takođe, u nekim slučajevima nije moguće popraviti elektroniku kod inverter klima iz razloga što postoji opcija da na tržištu nema odgovarajućih delova.',
    img: images.popravkaElektronike,
  },
  punjenjeDopunaFreona: {
    title: 'Punjenje/Dopuna freona',
    text: 'Dopuna klima uređaja gasom, odnosno freonom, je zasigurno jedna od najčešćih intervencija koje izvršavamo, ako izuzmemo montažu i servis klima uređaja. Često dobijamo pitanja kako da znamo da je klima uređaju potrebno punjenje freonom. Jasni pokazatelji toga su kada slabije hladi, pa čak i uopšte ne hladi. Takođe i kada slabije greje, a neretko se dešava i da se uopšte ne upali. Može se manifestovati i povećanom bukom iz spoljašnje jedinice zbog lošeg rada kompresora. To su stvari koje lično Vama predstavljaju problem u korišćenju klima uređaja, dok što se tiče same klime može doći do kvara kompresora. Upravo iz tog razloga je bitan redovan godišnji servis kako bi se proverila celokupna instalacija, zatim holenderi i gas (freon), kako ne bi dolazilo do većih kvarova koji će iziskivati mnogo veću potrošnju Vašeg novca. Kod punjenja klima uređaja postoji šansa da utvrdimo da je pukao holender ili var, samim tim klima je izgubila sav freon koji je iscureo. Provera se vrši uz pomoć posebnih manometara, a količina freona koji nedostaje može se dodati na osnovu radnog pritiska, specijalne vage ili uz pomoć posebne menzure za freon. Tako da pre nego što ponovo napunimo klimu moramo da ustanovimo šta je prouzrokovalo da dođe do curenja freona. Nakon što konstatujemo kvar, ‘’bacamo’’ se na posao kako bi isti što pre otklonili. Nakon toga punimo klima uređaj freonom koji je odgovarajući za klimu koju posedujete. Punjenje klima uređaja vršimo isključivo visokokvalitetnim originalnim freonima licenciranih proizvođača. Ne koristimo kineske freone, s obzirom da su i do nekoliko puta jeftiniji, sadrže veliki procenat vlage i veoma brzo i trajno oštećuju kompresor klima uređaja. Na kraju je potrebno vakumirati sistem. Uslugu punjenja klima uređaja izvršavamo na svim opštinama na teritoriji glavnog grada i uvek imamo slobodnu ekipu koja će doći na Vašu adresu i uspešno izvršiti navedenu uslugu.',
    img: images.punjenjeFreona,
  },
  zamenaKondezatora: {
    title: 'Zamena kondezatora',
    text: 'Kondenzator se u najvećem broju slučajeva kvari nakon 3-4 godine rada klime i to uglavnom na velikim temperaturama koje se kreću preko 40 stepeni. Kada zakaže kondenzator, neće se upaliti kompresor klime i samim tim klima neće moći da vrši ni grejanje, ni hlađenje. Uslugu zamene kondenzatora izvršavamo tako što prvo skinemo poklopac spoljne jedinice, a tu se nalaze dva kondenzatora: Kondenzator ventilatora i Kondenzator kompresora. Postoje različite veličine i jačine kondenzatora u zavisnosti od samog klima uređaja. Što se tiče kondenzatora ventilatora to je 1, 1.5, 2 i 1.5 + 5% pojačan. Dok što se tiče kondenzatora kompresora u pitanju su 25, 30, 35, 40, 45, 50mf. Kada ne radi ventilator dolazi do pregrevanja klima uređaja i ona se automatski gasi. Isto tako kada ne radi kompresor neke klime imaju bimetalnu zaštitu i same se gase kako ne bi došlo do oštećenja i vrlo verovatno ozbiljnijeg kvara koji može prouzrokovati potpuni prestanak korišćenja tog klima uređaja. Uslugu zamene kondenzatora izvršavamo na teritoriji celog grada, u našoj firmi su majstori sa dugogodišnjim iskustvom u ovoj uslužnoj oblasti i garantujemo da ćemo opravdati ukazano poverenje.',
    img: images.zamenaKondezatora,
  },
};
